# Generated by Django 4.0.4 on 2022-06-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_currency', models.CharField(max_length=50)),
                ('buy_currency_amount', models.FloatField()),
                ('sell_currency', models.CharField(max_length=50)),
                ('sell_currency_amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
