# Generated by Django 4.0.4 on 2022-08-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tickerdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerdata',
            name='currency',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
